# This is an example of user configuration, to be customized
owner: lAl
label: eden-level-1

database.host: your_db_host
database.port: 5432
database.name: your_db_name
database.user: your_db_user
database.password: "your_db_password"

monitoring.enabled: true # Set to false to stop measuring everything and posting results

capacitive_moisture_sensor.enabled: true
capacitive_moisture_sensor.devices:
  basil:
    port: 0
  pepper:
    port: 1
  kohlrabi:
    port: 2
  cherry_tomato:
    port: 3

si1145_sensor.enabled: true

bme680_sensor.enabled: true

scd30_sensor.enabled: true

as7341_sensor.enabled: true

raspberry_sensor.enabled: true

camera.enabled: true
camera.take_time: "18:00" # 24 hours time
camera.devices:
  top:
    video_device: 0 
    width: 1920
    height: 1080
    quality: 100
    num_samples: 5
    rotation: 0

relay_switch.enabled: true
relay_switch.devices:
  lights:
    port: 17 # digital port
    on_time: "9:00"
    off_time: "21:00"
    on_as_one: true # if true, setting 1 in the port will turn lights on
  fan:
    port: 16
    on_time: "11:00"
    off_time: "11:30"
    on_as_one: true
