# This is an example of user configuration, to be customized
owner: lAl
label: eden-level-1

database_host: your_db_host
database_port: 5432
database_name: your_db_name
database_user: your_db_user
database_password: "your_db_password"

picture_take_time: "18:00" # 24 hours time
picture_width: 1920
picture_height: 1080
picture_quality: 100
picture_num_samples: 5
picture_video_device: 0

enable_monitoring: true # Set to false to stop measuring everything and posting results
enable_capacitive_moisture_sensor: true
enable_si1145_sensor: true
enable_bme680_sensor: true
enable_scd30_sensor: true
enable_as7341_sensor: true
enable_raspberry_sensor: true
enable_picture_take: true
