# This is an example of user configuration, to be customized
owner: lAl
label: eden-level-1

db_host: your_db_host
db_port: 5432
db_user: your_db_user
db_password: "your_db_password"
db_database: your_db_name

picture_take_time: "18:00" # 24 hours time
picture_width: 1920
picture_height: 1080
picture_quality: 100

disable_monitoring: false # Set to true to temporarily stop measuring and posting results
disable_capacitive_moisture_sensor: false
disable_si1145_sensor: false
disable_bme680_sensor: false
disable_scd30_sensor: false
disable_as7341_sensor: false
disable_raspberry_sensor: false
disable_picture_take: false
