# This is an example of user configuration, to be customized
owner: lAl
label: eden-level-1

database_host: your_db_host
database_port: 5432
database_name: your_db_name
database_user: your_db_user
database_password: "your_db_password"

picture_take_time: "18:00" # 24 hours time
picture_width: 1920
picture_height: 1080
picture_quality: 100
picture_video_device: 0

disable_monitoring: false # Set to true to temporarily stop measuring and posting results
disable_capacitive_moisture_sensor: false
disable_si1145_sensor: false
disable_bme680_sensor: false
disable_scd30_sensor: false
disable_as7341_sensor: false
disable_raspberry_sensor: false
disable_picture_take: false
